title: "Buttons"
description:
  Here are all the buttons for use on this site. They specify which contexts they should be used in. All buttons will have the same gradient hover and focus state.

patterns:
  basic:
    title: "Basic Button"
    description: This button is used for most buttons used across the site. It should be used on cards.
    width: "12em"
    fields:
      - name: text
        type: string
        example: "Basic! Shop now"
      - name: url
        type: url
        example: "/products/"
  ghost:
    title: "Ghost Button"
    description: This button is used for buttons set on light backgrounds
    background: "--color-primary-light"
    fields:
      - name: text
        type: string
        example: "Boo! I'm a ghost"
      - name: url
        type: url
        example: "/products/"
  light:
    title: "Light Button"
    description: This button is used for buttons set on dark backgrounds.
    background: "--color-neutral"
    fields:
      - name: text
        type: string
        example: "Flash! Shop now"
      - name: url
        type: url
        example: "/products/"
  nav:
    title: "Nav Button"
    description: This button is used for the main nav links.
    fields:
      - name: text
        type: string
        example: "Artists"
      - name: url
        type: url
        example: "/products/"
      - name: icon
        type: string
        example: paint-brush-solid
