title: "Sections"
description:
  Here is the section format for use on the order summary card.

patterns:
  summary:
    title: "Order Summary"
    description: This is how the information for the Order Summary Card should be arranged.
    width: "90vw"
    fields:
      - name: item_1
        type: string
        example: "Alya, 20 minute"
      - name: quantity_1
        type: number
        example: 1
      - name: cost_1
        type: number
        example: 65
      - name: item_2
        type: string
        example: "Resting On My Yannies"
      - name: quantity_2
        type: number
        example: 1
      - name: cost_2
        type: number
        example: 69
      - name: total_cost
        type: number
        example: 134

  all-purpose-table:
    title: "All Purpose Table"
    description: This is for displaying totally unanticipated table information.
    width: "90vw"
    fields:
      - name: tr_1
        type: string
        example: "Title"
      - name: tr_2
        type: string
        example: "Title"
      - name: tr_3
        type: string
        example: "Title"
      - name: item_1_1
        type: string
        example: "Data"
      - name: item_1_2
        type: string
        example: "Data"
      - name: item_1_3
        type: string
        example: "Data"
      - name: item_2_1
        type: string
        example: "Data"
      - name: item_2_2
        type: string
        example: "Data"
      - name: item_2_3
        type: string
        example: "Data"
      - name: item_3_1
        type: string
        example: "Data"
      - name: item_3_2
        type: string
        example: "Data"
      - name: item_3_3
        type: string
        example: "Data"
      - name: item_4_1
        type: string
        example: "Data"
      - name: item_4_2
        type: string
        example: "Data"
      - name: item_4_3
        type: string
        example: "Data"
      - name: item_5_1
        type: string
        example: "Data"
      - name: item_5_2
        type: string
        example: "Data"
      - name: item_5_3
        type: string
        example: "Data"

  sale-banner:
    title: "Sale Banner"
    description: This is an all-purpose banner for sale related content.
    width: "90vw"
    fields:
      - name: text
        type: string
        example: "Check out our Sales!"
