title: "Cards"
description:
  Here are the different kinds of cards you will use on the site. These include product cards (that show artwork) and article cards.

patterns:
  basic:
    title: "Basic Card"
    description: This card is used for most cases used across the site. It should include a heading, some text, and a button.
    width: 95vw;
    fields:
      - name: title
        type: string
        example: "Hey! It's a card title"
      - name: text
        type: string
        example: "Blah blah blah here's some content"
        # required: false
      - name: aria
        type: string
        example: "This is a basic card"
      - name: button_text
        type: string
        example: "Card Button"
      - name: button_url
        type: url
        example: "#"

  artwork:
    title: "Artwork Card"
    description: This card is used to show an overview of artwork details.
    width: 20em;
    fields:
      - name: data
        type: object
        data:
          source: "site.products[0]"
          type: Product
      - name: img
        type: string
        example: "/images/artwork-1.jpg"
      - name: title
        type: string
        example: "Man in Profile, 30 minute"
      - name: artist
        type: string
        example: "Sabrina Madore"
      - name: cost
        type: num
        example: 55
      - name: media
        type: string
        example: "Watercolor on paper"
      - name: measurement
        type: string
        example: "9″x 9″"
      - name: aria
        type: string
        example: "This is an artwork card"

  preview:
    title: "Preview Card"
    description: This card is used on the homepage to link to major parts of the site (Feature artworks and artists).
    width: 95vw;
    fields:
      - name: title
        type: string
        example: "Featured Artist"
      - name: img
        type: string
        example: "/images/artwork-1.jpg"
      - name: card-img-title
        type: string
        example: "Feature Artist Name"
      - name: aria
        type: string
        example: "This is a preview card"
      - name: button_text
        type: string
        example: "Preview Button"
      - name: button_url
        type: string
        example: /products/


  artwork-only:
    title: "Artwork Only Card"
    description: This card is used on the product details page to display artwork.
    width: 65vw;
    fields:
      - name: data
        type: object
        data:
          source: "site.products[0]"
          type: Product
      - name: image
        type: string
        example: "/images/artwork-1.jpg"
      - name: aria
        type: string
        example: "This is an artwork-only card"

  product-description:
    title: "Product Description Card"
    description: This card is used on the product details page to display artwork.
    width: 95vw;
    fields:
      - name: data
        type: object
        data:
          source: "site.products[0]"
          type: Product
      - name: image
        type: string
        example: "/images/artwork-1.jpg"
      - name: title
        type: string
        example: "Man in Profile, 30 minute"
      - name: artist
        type: string
        example: "Sabrina Madore"
      - name: cost
        type: num
        example: 55
      - name: media
        type: string
        example: "Watercolor on paper"
      - name: measurement
        type: string
        example: "9″x 9″"
      - name: aria
        type: string
        example: "This is a product description card"

  checkout-summary:
    title: "Checkout Summary Card"
    description: This card is used exclusively as the beginning section of the checkout page. It displays a ″summary″ of users' orders
    width: 95vw;
    fields:
      - name: title
        type: string
        example: "Order Summary"
      - name: aria
        type: string
        example: "This is a checkout summary card"

  checkout-delivery:
    title: "Checkout Delivery Card"
    description: This card is used exclusively as the second section of the checkout page. It contains a form for users' delivery information
    width: 95vw;
    fields:
      - name: title
        type: string
        example: "Delivery"
      - name: aria
        type: string
        example: "This is a checkout delivery information card"

  checkout-payment:
    title: "Checkout Payment Card"
    description: This card is used exclusively as the third and final section of the checkout page. It contains a form for users' payment information
    width: 95vw;
    fields:
      - name: title
        type: string
        example: "Payment"
      - name: aria
        type: string
        example: "This is a checkout payment information card"
      - name: button_text
        type: string
        example: "Complete Purchase"
